[servers]

#control-node ansible-host=3.110.147.128
#control-node ansible-user=ubuntu
worker-node-1 ansible_host=65.2.180.230
worker-node-2 ansible_host=13.233.148.154
worker-node-1 ansible_user=ubuntu
worker-node-2 ansible_user=ubuntu

[all:vars]

ansible_ssh_private_key_file=/home/ubuntu/ansible-master-key
ansible_python_interpreter=/usr/bin/python3
ansible_host_key_checking=false
